### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by GeorgeWangnottaken**
changed the big header photos

reworked one past project description (streamliner upgrades) and added PCBway sponsor

got some nice discord feedback for the changes :D

### CODE REVIEW

**Review by savob — CHANGES_REQUESTED** [review]
Looks good for the most part, but two issues:

1. I noticed is that team members page is not linked to in the header for either the sign up or sponsor page.
2. You've put many new images in a new `img` folder under `resources/css` (`resources/css/img/`), can you please move them to the `resourses/img` folder with the rest of our photos if possible. 

As an aside, can we delete unused media from this repository? It's wasting space and if we will need any of it again I believe we can fish it out of either our own media archives or by going back in this repository's commit history.

**Comment by savob** [comment]
I see that these changes have to do with files referenced in the `.css` files. Can we not refer to folders outside of where the `.css` files reside?

**Comment by GeorgeWangnottaken** [comment]
1. made navigation headers consistent and added a little disclaimer about the sketchiness of current team member list now that the page is easier to access
2. renamed img folder in css for clarity: i fricking hate that folder and with a passion but i have decided to let it continue its  wretched existence and move away its reference outside of .css

i also removed some old team member photos since there are a bunch of those

I'd appreciate if you pay extra attention to make sure the website photos are all still well behaved after my reshuffling/renaming!

thanks again for thoughtful feedback savooooo <3

**Review by savob — APPROVED** [review]
Good work.

Going forward lets try to remove more of our unused media and touch up the team member page to clarify that it list past and present team members, possibly making different sections as well as updating/correcting the info already present.

**Pull request merged**
